apiVersion: v1
kind: Service
metadata:
  name: shortcut-app-service
  namespace: shortcut
spec:
  selector:
    app: shortcut-app-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortcut-app-service
  namespace: shortcut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortcut-app-service
  template:
    metadata:
      labels:
        app: shortcut-app-service
    spec:
      containers:
        - name: app
          image: shortcut_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9090
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          env:
            - name: CLICKHOUSE_DSN
              value: "clickhouse.shortcut.svc.cluster.local:8123"
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              value: "password123"
            - name: METRICS_ADDR
              value: ":9090"
            - name: WEB_API_ADDR
              value: ":8080"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shortcut-app-service-hpa
  namespace: shortcut
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shortcut-app-service
  minReplicas: 1
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
